### ISSUE TITLE
problem in training

### ISSUE THREAD

**Issue by raymond00000** [RuiCaiNLP/SRL_DEP#1]
Hi, 

I tried to run the code. 
I always got below exception when it is 4300 iterations. 

any idea on why this error? many thanks.

4000
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SRLloss
tensor(0.0717, device='cuda:0', grad_fn=<NllLossBackward>)
[epoch 0, 4000 * 30]
start test...
now dev test
[<enumerate object at 0x7f64093eee10>]
9963.0
12550.0
13865.0
Precision: 0.8627586206896551 recall: 0.8064964046615423 F1: 0.833679354094579
Precision: 0.7938012907338061 recall: 0.7185719437432384 F1: 0.7542656933373186
5770.0
6390.0
disambiguate accuraccy: 0.9029733959311425
Best F1: 0.7423703852543445
New best, model saved
4100
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SRLloss
tensor(0.0752, device='cuda:0', grad_fn=<NllLossBackward>)
4200
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SRLloss
tensor(0.0999, device='cuda:0', grad_fn=<NllLossBackward>)
4300
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SRLloss
tensor(0.0830, device='cuda:0', grad_fn=<NllLossBackward>)
Traceback (most recent call last):
  File "/media/works/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/media/works/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/works/srl/SRL_DEP/nnet/run/srl/run.py", line 290, in <module>
    SRLRunner().run()
  File "/media/works/srl/SRL_DEP/nnet/run/runner.py", line 114, in run
    params_path=a.params_path
  File "/media/works/srl/SRL_DEP/nnet/training.py", line 136, in train
    targets, specific_dep_tags_in, specific_dep_relations_in)
  File "/media/works/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/works/srl/SRL_DEP/nnet/nn_models/Biaffine_SRL_only_VR.py", line 210, in forward
    fixed_embeds = fixed_embeds.view(self.batch_size, len(sentence[0]), self.word_emb_dim)
RuntimeError: invalid argument 2: size **'[30 x 17 x 100]' is invalid for input with 6800 elements** at /pytorch/aten/src/TH/THStorage.cpp:84

**Comment by raymond00000** [comment]
training size must a multiple of 30 (batch si), else (8) last batch will cause this exception.
